import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = path.join(root, "nextsignal/mcp/ui/generated");
const result = await build({
  entryPoints: [path.join(root, "nextsignal/mcp/ui/shopping-app.tsx")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  write: false,
  jsx: "automatic"
});

const javascript = result.outputFiles[0]?.text.replaceAll("</script", "<\\/script");

if (!javascript) throw new Error("The MCP App bundle did not produce JavaScript.");

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light dark" />
    <title>Shopping list</title>
  </head>
  <body>
    <div id="root"></div>
    <script>${javascript}</script>
  </body>
</html>`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(
  path.join(outputDirectory, "shopping-app-html.ts"),
  `// Generated by scripts/build-mcp-app.mjs. Do not edit.\nexport const shoppingAppHtml = ${JSON.stringify(html)};\n`
);
